# Turns configs/nids.csv into initializers for the table main.cpp compiles in:
#   cmake -DINPUT=<nids.csv> -DOUTPUT=<nid_table.inc> -P embed_nids.cmake
# Each `library,nid,name` line becomes {"library", 0xNIDu, "name"},
# and the file is only rewritten when its content changes.
file(STRINGS "${INPUT}" lines)
set(content "// Generated from configs/nids.csv by profiles/mhp2g/tools/embed_nids.cmake.\n")
set(line_number 0)
foreach(line IN LISTS lines)
    math(EXPR line_number "${line_number} + 1")
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()
    if(NOT line MATCHES "^([A-Za-z0-9_]+),(0[xX])?([0-9A-Fa-f]+),([A-Za-z0-9_]+)$")
        message(FATAL_ERROR "${INPUT}:${line_number}: expected library,nid,name")
    endif()
    string(APPEND content "{\"${CMAKE_MATCH_1}\", 0x${CMAKE_MATCH_3}u, \"${CMAKE_MATCH_4}\"},\n")
endforeach()
set(previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
